import 'package:flutter/material.dart';
import 'theme_data.dart';

class AppThemes {
  // Default Shadcn theme
  static final defaultTheme = AppThemeData(
    name: 'default',
    displayName: 'Default',
    primaryColor: const Color(0xFF0F172A),
    lightColors: const AppColorScheme(
      background: Color(0xFFFFFFFF),
      onBackground: Color(0xFF020817),
      surface: Color(0xFFFFFFFF),
      onSurface: Color(0xFF020817),
      surfaceVariant: Color(0xFFFFFFFF),
      onSurfaceVariant: Color(0xFF64748B),
      primary: Color(0xFF0F172A),
      onPrimary: Color(0xFFF8FAFC),
      secondary: Color(0xFFF1F5F9),
      onSecondary: Color(0xFF0F172A),
      accent: Color(0xFFF1F5F9),
      onAccent: Color(0xFF0F172A),
      error: Color(0xFFEF4444),
      onError: Color(0xFFF8FAFC),
      border: Color(0xFFE2E8F0),
      borderVariant: Color(0xFFCBD5E1),
    ),
    darkColors: const AppColorScheme(
      background: Color(0xFF020817),
      onBackground: Color(0xFFF8FAFC),
      surface: Color(0xFF020817),
      onSurface: Color(0xFFF8FAFC),
      surfaceVariant: Color(0xFF020817),
      onSurfaceVariant: Color(0xFF94A3B8),
      primary: Color(0xFFF8FAFC),
      onPrimary: Color(0xFF0F172A),
      secondary: Color(0xFF1E293B),
      onSecondary: Color(0xFFF8FAFC),
      accent: Color(0xFF1E293B),
      onAccent: Color(0xFFF8FAFC),
      error: Color(0xFF7F1D1D),
      onError: Color(0xFFF8FAFC),
      border: Color(0xFF1E293B),
      borderVariant: Color(0xFF334155),
    ),
  );

  // Blue theme
  static final blueTheme = AppThemeData(
    name: 'blue',
    displayName: 'Ocean Blue',
    primaryColor: const Color(0xFF2563EB),
    lightColors: const AppColorScheme(
      background: Color(0xFFFFFFFF),
      onBackground: Color(0xFF1E293B),
      surface: Color(0xFFFFFFFF),
      onSurface: Color(0xFF1E293B),
      surfaceVariant: Color(0xFFFFFFFF),
      onSurfaceVariant: Color(0xFF64748B),
      primary: Color(0xFF2563EB),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFDBEAFE),
      onSecondary: Color(0xFF1E40AF),
      accent: Color(0xFFEFF6FF),
      onAccent: Color(0xFF1E40AF),
      error: Color(0xFFDC2626),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFFE2E8F0),
      borderVariant: Color(0xFFCBD5E1),
    ),
    darkColors: const AppColorScheme(
      background: Color(0xFF020817),
      onBackground: Color(0xFFF8FAFC),
      surface: Color(0xFF020817),
      onSurface: Color(0xFFF8FAFC),
      surfaceVariant: Color(0xFF020817),
      onSurfaceVariant: Color(0xFF94A3B8),
      primary: Color(0xFF3B82F6),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF1E293B),
      onSecondary: Color(0xFFF8FAFC),
      accent: Color(0xFF1E293B),
      onAccent: Color(0xFFF8FAFC),
      error: Color(0xFF991B1B),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFF1E293B),
      borderVariant: Color(0xFF334155),
    ),
  );

  // Green theme
  static final greenTheme = AppThemeData(
    name: 'green',
    displayName: 'Forest Green',
    primaryColor: const Color(0xFF16A34A),
    lightColors: const AppColorScheme(
      background: Color(0xFFFFFFFF),
      onBackground: Color(0xFF14532D),
      surface: Color(0xFFFFFFFF),
      onSurface: Color(0xFF14532D),
      surfaceVariant: Color(0xFFFFFFFF),
      onSurfaceVariant: Color(0xFF166534),
      primary: Color(0xFF16A34A),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFDCFCE7),
      onSecondary: Color(0xFF14532D),
      accent: Color(0xFFECFDF5),
      onAccent: Color(0xFF14532D),
      error: Color(0xFFDC2626),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFFE2E8F0),
      borderVariant: Color(0xFFCBD5E1),
    ),
    darkColors: const AppColorScheme(
      background: Color(0xFF020817),
      onBackground: Color(0xFFF8FAFC),
      surface: Color(0xFF020817),
      onSurface: Color(0xFFF8FAFC),
      surfaceVariant: Color(0xFF020817),
      onSurfaceVariant: Color(0xFF94A3B8),
      primary: Color(0xFF22C55E),
      onPrimary: Color(0xFF000000),
      secondary: Color(0xFF1E293B),
      onSecondary: Color(0xFFF8FAFC),
      accent: Color(0xFF1E293B),
      onAccent: Color(0xFFF8FAFC),
      error: Color(0xFF991B1B),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFF1E293B),
      borderVariant: Color(0xFF334155),
    ),
  );

  // Purple theme
  static final purpleTheme = AppThemeData(
    name: 'purple',
    displayName: 'Royal Purple',
    primaryColor: const Color(0xFF7C3AED),
    lightColors: const AppColorScheme(
      background: Color(0xFFFFFFFF),
      onBackground: Color(0xFF581C87),
      surface: Color(0xFFFFFFFF),
      onSurface: Color(0xFF581C87),
      surfaceVariant: Color(0xFFFFFFFF),
      onSurfaceVariant: Color(0xFF7C2D92),
      primary: Color(0xFF7C3AED),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFE9D5FF),
      onSecondary: Color(0xFF581C87),
      accent: Color(0xFFF3E8FF),
      onAccent: Color(0xFF581C87),
      error: Color(0xFFDC2626),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFFE2E8F0),
      borderVariant: Color(0xFFCBD5E1),
    ),
    darkColors: const AppColorScheme(
      background: Color(0xFF020817),
      onBackground: Color(0xFFF8FAFC),
      surface: Color(0xFF020817),
      onSurface: Color(0xFFF8FAFC),
      surfaceVariant: Color(0xFF020817),
      onSurfaceVariant: Color(0xFF94A3B8),
      primary: Color(0xFF8B5CF6),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF1E293B),
      onSecondary: Color(0xFFF8FAFC),
      accent: Color(0xFF1E293B),
      onAccent: Color(0xFFF8FAFC),
      error: Color(0xFF991B1B),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFF1E293B),
      borderVariant: Color(0xFF334155),
    ),
  );

  // Orange theme
  static final orangeTheme = AppThemeData(
    name: 'orange',
    displayName: 'Sunset Orange',
    primaryColor: const Color(0xFFEA580C),
    lightColors: const AppColorScheme(
      background: Color(0xFFFFFFFF),
      onBackground: Color(0xFF9A3412),
      surface: Color(0xFFFFFFFF),
      onSurface: Color(0xFF9A3412),
      surfaceVariant: Color(0xFFFFFFFF),
      onSurfaceVariant: Color(0xFFC2410C),
      primary: Color(0xFFEA580C),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFFFE4CC),
      onSecondary: Color(0xFF9A3412),
      accent: Color(0xFFFFF7ED),
      onAccent: Color(0xFF9A3412),
      error: Color(0xFFDC2626),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFFE2E8F0),
      borderVariant: Color(0xFFCBD5E1),
    ),
    darkColors: const AppColorScheme(
      background: Color(0xFF020817),
      onBackground: Color(0xFFF8FAFC),
      surface: Color(0xFF020817),
      onSurface: Color(0xFFF8FAFC),
      surfaceVariant: Color(0xFF020817),
      onSurfaceVariant: Color(0xFF94A3B8),
      primary: Color(0xFFF97316),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF1E293B),
      onSecondary: Color(0xFFF8FAFC),
      accent: Color(0xFF1E293B),
      onAccent: Color(0xFFF8FAFC),
      error: Color(0xFF991B1B),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFF1E293B),
      borderVariant: Color(0xFF334155),
    ),
  );

  // Midnight theme - Pure black aesthetic
  static final midnightTheme = AppThemeData(
    name: 'midnight',
    displayName: 'Midnight Black',
    primaryColor: const Color(0xFF000000),
    lightColors: const AppColorScheme(
      background: Color(0xFFFAFAFA),
      onBackground: Color(0xFF000000),
      surface: Color(0xFFFAFAFA),
      onSurface: Color(0xFF000000),
      surfaceVariant: Color(0xFFFAFAFA),
      onSurfaceVariant: Color(0xFF404040),
      primary: Color(0xFF000000),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFF5F5F5),
      onSecondary: Color(0xFF000000),
      accent: Color(0xFFF0F0F0),
      onAccent: Color(0xFF000000),
      error: Color(0xFFDC2626),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFFE5E5E5),
      borderVariant: Color(0xFFD4D4D4),
    ),
    darkColors: const AppColorScheme(
      background: Color(0xFF000000),
      onBackground: Color(0xFFFFFFFF),
      surface: Color(0xFF000000),
      onSurface: Color(0xFFFFFFFF),
      surfaceVariant: Color(0xFF000000),
      onSurfaceVariant: Color(0xFFA1A1AA),
      primary: Color(0xFFFFFFFF),
      onPrimary: Color(0xFF000000),
      secondary: Color(0xFF1A1A1A),
      onSecondary: Color(0xFFFFFFFF),
      accent: Color(0xFF1A1A1A),
      onAccent: Color(0xFFFFFFFF),
      error: Color(0xFFEF4444),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFF2A2A2A),
      borderVariant: Color(0xFF3A3A3A),
    ),
  );

  // Indigo theme
  static final indigoTheme = AppThemeData(
    name: 'indigo',
    displayName: 'Deep Indigo',
    primaryColor: const Color(0xFF4F46E5),
    lightColors: const AppColorScheme(
      background: Color(0xFFFFFFFF),
      onBackground: Color(0xFF312E81),
      surface: Color(0xFFFFFFFF),
      onSurface: Color(0xFF312E81),
      surfaceVariant: Color(0xFFFFFFFF),
      onSurfaceVariant: Color(0xFF3730A3),
      primary: Color(0xFF4F46E5),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFE0E7FF),
      onSecondary: Color(0xFF312E81),
      accent: Color(0xFFF0F9FF),
      onAccent: Color(0xFF312E81),
      error: Color(0xFFDC2626),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFFE2E8F0),
      borderVariant: Color(0xFFCBD5E1),
    ),
    darkColors: const AppColorScheme(
      background: Color(0xFF020817),
      onBackground: Color(0xFFF8FAFC),
      surface: Color(0xFF020817),
      onSurface: Color(0xFFF8FAFC),
      surfaceVariant: Color(0xFF020817),
      onSurfaceVariant: Color(0xFF94A3B8),
      primary: Color(0xFF6366F1),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF1E293B),
      onSecondary: Color(0xFFF8FAFC),
      accent: Color(0xFF1E293B),
      onAccent: Color(0xFFF8FAFC),
      error: Color(0xFF991B1B),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFF1E293B),
      borderVariant: Color(0xFF334155),
    ),
  );

  // Cream theme - Warm minimal
  static final creamTheme = AppThemeData(
    name: 'cream',
    displayName: 'Cream Minimal',
    primaryColor: const Color(0xFF8B5A2B),
    lightColors: const AppColorScheme(
      background: Color(0xFFFFFDF7),
      onBackground: Color(0xFF3C2415),
      surface: Color(0xFFFFFDF7),
      onSurface: Color(0xFF3C2415),
      surfaceVariant: Color(0xFFFFFDF7),
      onSurfaceVariant: Color(0xFF6B4423),
      primary: Color(0xFF8B5A2B),
      onPrimary: Color(0xFFFFFDF7),
      secondary: Color(0xFFF7F3E9),
      onSecondary: Color(0xFF3C2415),
      accent: Color(0xFFFAF8F1),
      onAccent: Color(0xFF3C2415),
      error: Color(0xFFDC2626),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFFE7E2D7),
      borderVariant: Color(0xFFD6CFC0),
    ),
    darkColors: const AppColorScheme(
      background: Color(0xFF020817),
      onBackground: Color(0xFFF8FAFC),
      surface: Color(0xFF020817),
      onSurface: Color(0xFFF8FAFC),
      surfaceVariant: Color(0xFF020817),
      onSurfaceVariant: Color(0xFF94A3B8),
      primary: Color(0xFFD97706),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF1E293B),
      onSecondary: Color(0xFFF8FAFC),
      accent: Color(0xFF1E293B),
      onAccent: Color(0xFFF8FAFC),
      error: Color(0xFF991B1B),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFF1E293B),
      borderVariant: Color(0xFF334155),
    ),
  );

  // Cyber theme - Neon tech aesthetic
  static final cyberTheme = AppThemeData(
    name: 'cyber',
    displayName: 'Cyber Neon',
    primaryColor: const Color(0xFF00F5FF),
    lightColors: const AppColorScheme(
      background: Color(0xFFF8FFFE),
      onBackground: Color(0xFF003D40),
      surface: Color(0xFFF8FFFE),
      onSurface: Color(0xFF003D40),
      surfaceVariant: Color(0xFFF8FFFE),
      onSurfaceVariant: Color(0xFF006064),
      primary: Color(0xFF00ACC1),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFE0F7FA),
      onSecondary: Color(0xFF003D40),
      accent: Color(0xFFF1FCFD),
      onAccent: Color(0xFF003D40),
      error: Color(0xFFDC2626),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFFB2EBF2),
      borderVariant: Color(0xFF80DEEA),
    ),
    darkColors: const AppColorScheme(
      background: Color(0xFF020817),
      onBackground: Color(0xFFF8FAFC),
      surface: Color(0xFF020817),
      onSurface: Color(0xFFF8FAFC),
      surfaceVariant: Color(0xFF020817),
      onSurfaceVariant: Color(0xFF94A3B8),
      primary: Color(0xFF00F5FF),
      onPrimary: Color(0xFF000000),
      secondary: Color(0xFF1E293B),
      onSecondary: Color(0xFFF8FAFC),
      accent: Color(0xFF1E293B),
      onAccent: Color(0xFFF8FAFC),
      error: Color(0xFF991B1B),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFF1E293B),
      borderVariant: Color(0xFF334155),
    ),
  );

  // Slate theme
  static final slateTheme = AppThemeData(
    name: 'slate',
    displayName: 'Slate Mono',
    primaryColor: const Color(0xFF475569),
    lightColors: const AppColorScheme(
      background: Color(0xFFFFFFFF),
      onBackground: Color(0xFF1E293B),
      surface: Color(0xFFFFFFFF),
      onSurface: Color(0xFF1E293B),
      surfaceVariant: Color(0xFFFFFFFF),
      onSurfaceVariant: Color(0xFF64748B),
      primary: Color(0xFF475569),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFF1F5F9),
      onSecondary: Color(0xFF1E293B),
      accent: Color(0xFFF8FAFC),
      onAccent: Color(0xFF1E293B),
      error: Color(0xFFDC2626),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFFE2E8F0),
      borderVariant: Color(0xFFCBD5E1),
    ),
    darkColors: const AppColorScheme(
      background: Color(0xFF020817),
      onBackground: Color(0xFFF8FAFC),
      surface: Color(0xFF020817),
      onSurface: Color(0xFFF8FAFC),
      surfaceVariant: Color(0xFF020817),
      onSurfaceVariant: Color(0xFF94A3B8),
      primary: Color(0xFF64748B),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF1E293B),
      onSecondary: Color(0xFFF8FAFC),
      accent: Color(0xFF1E293B),
      onAccent: Color(0xFFF8FAFC),
      error: Color(0xFF991B1B),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFF1E293B),
      borderVariant: Color(0xFF334155),
    ),
  );

  // All themes list
  static final List<AppThemeData> allThemes = [
    defaultTheme,
    blueTheme,
    greenTheme,
    purpleTheme,
    orangeTheme,
    midnightTheme,
    indigoTheme,
    creamTheme,
    cyberTheme,
    slateTheme,
    roseTheme,
    lavenderTheme,
    mintTheme,
    peachTheme,
    iceTheme,
  ];

  // Rose theme - Soft pink aesthetic
  static final roseTheme = AppThemeData(
    name: 'rose',
    displayName: 'Rose Blush',
    primaryColor: const Color(0xFFE11D48),
    lightColors: const AppColorScheme(
      background: Color(0xFFFDF2F8),
      onBackground: Color(0xFF881337),
      surface: Color(0xFFFDF2F8),
      onSurface: Color(0xFF881337),
      surfaceVariant: Color(0xFFFDF2F8),
      onSurfaceVariant: Color(0xFF9F1239),
      primary: Color(0xFFE11D48),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFFFE4E6),
      onSecondary: Color(0xFF881337),
      accent: Color(0xFFFFF1F2),
      onAccent: Color(0xFF881337),
      error: Color(0xFFDC2626),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFFFCE7F3),
      borderVariant: Color(0xFFF9A8D4),
    ),
    darkColors: const AppColorScheme(
      background: Color(0xFF1A0B0F), // Dark rose tinted
      onBackground: Color(0xFFFDF2F8),
      surface: Color(0xFF1A0B0F),
      onSurface: Color(0xFFFDF2F8),
      surfaceVariant: Color(0xFF1A0B0F),
      onSurfaceVariant: Color(0xFFE4A0B7),
      primary: Color(0xFFF43F5E),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF2D1B20),
      onSecondary: Color(0xFFFDF2F8),
      accent: Color(0xFF2D1B20),
      onAccent: Color(0xFFFDF2F8),
      error: Color(0xFF991B1B),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFF2D1B20),
      borderVariant: Color(0xFF3D2B30),
    ),
  );

  // Lavender theme
  static final lavenderTheme = AppThemeData(
    name: 'lavender',
    displayName: 'Lavender Mist',
    primaryColor: const Color(0xFF8B5CF6),
    lightColors: const AppColorScheme(
      background: Color(0xFFFAF5FF),
      onBackground: Color(0xFF4C1D95),
      surface: Color(0xFFFAF5FF),
      onSurface: Color(0xFF4C1D95),
      surfaceVariant: Color(0xFFFAF5FF),
      onSurfaceVariant: Color(0xFF6D28D9),
      primary: Color(0xFF8B5CF6),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFF3E8FF),
      onSecondary: Color(0xFF4C1D95),
      accent: Color(0xFFF5F3FF),
      onAccent: Color(0xFF4C1D95),
      error: Color(0xFFDC2626),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFFE9D5FF),
      borderVariant: Color(0xFFD8B4FE),
    ),
    darkColors: const AppColorScheme(
      background: Color(0xFF0F0A1A), // Dark lavender tinted
      onBackground: Color(0xFFFAF5FF),
      surface: Color(0xFF0F0A1A),
      onSurface: Color(0xFFFAF5FF),
      surfaceVariant: Color(0xFF0F0A1A),
      onSurfaceVariant: Color(0xFFC4B5FD),
      primary: Color(0xFFA855F7),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF1E1A2D),
      onSecondary: Color(0xFFFAF5FF),
      accent: Color(0xFF1E1A2D),
      onAccent: Color(0xFFFAF5FF),
      error: Color(0xFF991B1B),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFF1E1A2D),
      borderVariant: Color(0xFF2E2A3D),
    ),
  );

  // Mint theme
  static final mintTheme = AppThemeData(
    name: 'mint',
    displayName: 'Fresh Mint',
    primaryColor: const Color(0xFF10B981),
    lightColors: const AppColorScheme(
      background: Color(0xFFF0FDF4),
      onBackground: Color(0xFF064E3B),
      surface: Color(0xFFF0FDF4),
      onSurface: Color(0xFF064E3B),
      surfaceVariant: Color(0xFFF0FDF4),
      onSurfaceVariant: Color(0xFF047857),
      primary: Color(0xFF10B981),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFD1FAE5),
      onSecondary: Color(0xFF064E3B),
      accent: Color(0xFFECFDF5),
      onAccent: Color(0xFF064E3B),
      error: Color(0xFFDC2626),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFFA7F3D0),
      borderVariant: Color(0xFF6EE7B7),
    ),
    darkColors: const AppColorScheme(
      background: Color(0xFF0A1A0F), // Dark mint tinted
      onBackground: Color(0xFFF0FDF4),
      surface: Color(0xFF0A1A0F),
      onSurface: Color(0xFFF0FDF4),
      surfaceVariant: Color(0xFF0A1A0F),
      onSurfaceVariant: Color(0xFF86EFAC),
      primary: Color(0xFF34D399),
      onPrimary: Color(0xFF000000),
      secondary: Color(0xFF1A2D1E),
      onSecondary: Color(0xFFF0FDF4),
      accent: Color(0xFF1A2D1E),
      onAccent: Color(0xFFF0FDF4),
      error: Color(0xFF991B1B),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFF1A2D1E),
      borderVariant: Color(0xFF2A3D2E),
    ),
  );

  // Peach theme
  static final peachTheme = AppThemeData(
    name: 'peach',
    displayName: 'Peach Soft',
    primaryColor: const Color(0xFFF97316),
    lightColors: const AppColorScheme(
      background: Color(0xFFFFF7ED),
      onBackground: Color(0xFF9A3412),
      surface: Color(0xFFFFF7ED),
      onSurface: Color(0xFF9A3412),
      surfaceVariant: Color(0xFFFFF7ED),
      onSurfaceVariant: Color(0xFFEA580C),
      primary: Color(0xFFF97316),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFFED7AA),
      onSecondary: Color(0xFF9A3412),
      accent: Color(0xFFFFEDD5),
      onAccent: Color(0xFF9A3412),
      error: Color(0xFFDC2626),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFFFED7AA),
      borderVariant: Color(0xFFFDBB7A),
    ),
    darkColors: const AppColorScheme(
      background: Color(0xFF1A0F0A), // Dark peach tinted
      onBackground: Color(0xFFFFF7ED),
      surface: Color(0xFF1A0F0A),
      onSurface: Color(0xFFFFF7ED),
      surfaceVariant: Color(0xFF1A0F0A),
      onSurfaceVariant: Color(0xFFFED7AA),
      primary: Color(0xFFFB923C),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFF2D1F1A),
      onSecondary: Color(0xFFFFF7ED),
      accent: Color(0xFF2D1F1A),
      onAccent: Color(0xFFFFF7ED),
      error: Color(0xFF991B1B),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFF2D1F1A),
      borderVariant: Color(0xFF3D2F2A),
    ),
  );

  // Ice theme
  static final iceTheme = AppThemeData(
    name: 'ice',
    displayName: 'Ice Crystal',
    primaryColor: const Color(0xFF06B6D4),
    lightColors: const AppColorScheme(
      background: Color(0xFFF0FDFF),
      onBackground: Color(0xFF164E63),
      surface: Color(0xFFF0FDFF),
      onSurface: Color(0xFF164E63),
      surfaceVariant: Color(0xFFF0FDFF),
      onSurfaceVariant: Color(0xFF0891B2),
      primary: Color(0xFF06B6D4),
      onPrimary: Color(0xFFFFFFFF),
      secondary: Color(0xFFA5F3FC),
      onSecondary: Color(0xFF164E63),
      accent: Color(0xFFCFFAFE),
      onAccent: Color(0xFF164E63),
      error: Color(0xFFDC2626),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFFA5F3FC),
      borderVariant: Color(0xFF67E8F9),
    ),
    darkColors: const AppColorScheme(
      background: Color(0xFF0A1A1F), // Dark ice blue tinted
      onBackground: Color(0xFFF0FDFF),
      surface: Color(0xFF0A1A1F),
      onSurface: Color(0xFFF0FDFF),
      surfaceVariant: Color(0xFF0A1A1F),
      onSurfaceVariant: Color(0xFF67E8F9),
      primary: Color(0xFF22D3EE),
      onPrimary: Color(0xFF000000),
      secondary: Color(0xFF1A2D2F),
      onSecondary: Color(0xFFF0FDFF),
      accent: Color(0xFF1A2D2F),
      onAccent: Color(0xFFF0FDFF),
      error: Color(0xFF991B1B),
      onError: Color(0xFFFFFFFF),
      border: Color(0xFF1A2D2F),
      borderVariant: Color(0xFF2A3D3F),
    ),
  );
}